# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.game_engine:
    class: AppBundle\Service\GameEngine

  app.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    shared: false

  app.repository.game:
    parent: app.repository
    arguments: ['AppBundle:Game']

  app.repository.move_type:
    parent: app.repository
    arguments: ['AppBundle:MoveType']

  validator.game_guid_exists:
    class: AppBundle\Validator\Constraints\GameGuidExistsValidator
    arguments: ['@app.repository.game']
    tags:
      - { name: validator.constraint_validator }

  validator.move_exists:
    class: AppBundle\Validator\Constraints\MoveExistsValidator
    arguments: ['@app.repository.move_type']
    tags:
      - { name: validator.constraint_validator }

  validator.move_belongs_to_game_type:
    class: AppBundle\Validator\Constraints\MoveBelongsToGameTypeValidator
    arguments: ['@app.repository.game', '@app.repository.move_type']
    tags:
      - { name: validator.constraint_validator }