version: "2"
services:
  node:
    container_name: rockpaperscissor-webapp-node
    image: rockpaperscissor-webapp-node
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/application

  apache:
    container_name: rockpaperscissor-webapp-apache
    image: rockpaperscissor-webapp-apache
    ports:
      - "80:80"
    volumes:
      - ./backend:/opt/application
    links:
      - php
    depends_on:
      - node

  php:
    container_name: rockpaperscissor-webapp-php
    image: rockpaperscissor-webapp-php
    ports:
      - "9000:9000"
      - "22:22"
    volumes:
      - ./backend:/opt/application
    links:
      - db
      - mailhog

  db:
    container_name: rockpaperscissor-webapp-mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r00t

  mailhog:
    container_name: rockpaperscissor-webapp-mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"