version: "2"
services:
  backend:
    container_name: rockpaperscissor-webapp-php
    image: rockpaperscissor-webapp-php
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/opt/application

  frontend:
    container_name: rockpaperscissor-webapp-react
    image: rockpaperscissor-webapp-react
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/opt/application

  db:
    container_name: rockpaperscissor-webapp-mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r00t