# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Player:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: AppBundle:Player
                property: username

    firewalls:
        login:
            pattern:  ^/api/v1/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/v1/login
                require_previous_session: false
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        register:
            pattern:  ^/api/v1/register
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api/v1
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/api/v1/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }
