<?php

namespace AppBundle\Repository;

/**
 * GameSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameSetRepository extends \Doctrine\ORM\EntityRepository
{
}
