<?php

namespace AppBundle\Repository;

/**
 * GameTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
