<?php

namespace AppBundle\Repository;

/**
 * MoveTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
